import http from "k6/http";
import { check, sleep } from "k6";
import exec from "k6/execution";
import { Trend } from "k6/metrics";
import {
  randomString,
  randomIntBetween,
} from "https://jslib.k6.io/k6-utils/1.4.0/index.js";

/*
 * Nexora backend: smoke test (all APIs) + role-based load / capacity test.
 *
 * Smoke:
 *   k6 run -e MODE=smoke -e ADMIN_EMAIL=... -e ADMIN_PASSWORD=... full-test.js
 *
 * Load, baseline (17 users, no chat):
 *   k6 run -e MODE=load -e CHAT_VUS=0 -e ADMIN_EMAIL=... -e ADMIN_PASSWORD=... --summary-export=result.json full-test.js
 *
 * Capacity test (SCALE multiplies students + teachers; 1 = 17 users, 2 = 33, 4 = 65, 8 = 129, 16 = 257):
 *   k6 run -e MODE=load -e CHAT_VUS=0 -e SCALE=4 -e ADMIN_EMAIL=... -e ADMIN_PASSWORD=... --summary-export=result-x4.json full-test.js
 *
 * Load with chat (start small, needs Hugging Face credits):
 *   k6 run -e MODE=load -e CHAT_VUS=2 -e ADMIN_EMAIL=... -e ADMIN_PASSWORD=... full-test.js
 */

const BASE = __ENV.BASE_URL || "http://localhost:5000";
const MODE = __ENV.MODE || "smoke"; // smoke | load
const CHAT_VUS = Number(__ENV.CHAT_VUS === undefined ? 3 : __ENV.CHAT_VUS); // 0 = skip chat
const SCALE = Number(__ENV.SCALE || 1); // load multiplier (1 = baseline)
const STUDENTS = Number(__ENV.STUDENTS || 10); // student accounts created in setup
const TEACHERS = Number(__ENV.TEACHERS || 4); // teacher accounts created in setup
const J = { "Content-Type": "application/json" };
const pick = (a) => a[randomIntBetween(0, a.length - 1)];

// latency of SUCCESSFUL chat answers only (failed calls return fast and would skew p95)
const chatOkMs = new Trend("chat_success_ms", true);

const P = {
  register: "/api/auth/register",
  login: "/api/auth/login",
  chat: "/api/chat",
  chatField: "message", // change if your chat controller reads another field
};

// role -> endpoints that role should be able to call
const ENDPOINTS = [
  { role: "teacher", m: "GET", p: "/api/tasks" },
  { role: "teacher", m: "GET", p: "/api/users/students" },
  { role: "teacher", m: "GET", p: "/api/users/stats" },
  { role: "student", m: "GET", p: "/api/tasks" },
  { role: "student", m: "GET", p: "/api/quizzes" },
  { role: "student", m: "GET", p: "/api/quizzes/attempts/me" },
  { role: "student", m: "GET", p: "/api/users/leaderboard" },
  { role: "admin", m: "GET", p: "/api/admin/stats" },
  { role: "admin", m: "GET", p: "/api/admin/users" },
  { role: "admin", m: "GET", p: "/api/admin/users/pending" },
  { role: "student", m: "POST", p: P.chat, chat: true },
];

const FALLBACK_PROMPTS = [
  "What is global warming?",
  "How can I reduce plastic waste?",
  "Explain the greenhouse effect",
  "What is renewable energy?",
  "Why are forests important?",
];

// ---------- helpers ----------
const auth = (t, extra = {}) => ({
  headers: { ...J, Authorization: `Bearer ${t}` },
  ...extra,
});

const okStatus = (r) => r.status >= 200 && r.status < 300;

const tokenOf = (r) => {
  try {
    const j = r.json();
    return j.token || j.accessToken || (j.data && j.data.token) || "";
  } catch (e) {
    return "";
  }
};

const idOf = (r) => {
  try {
    const j = r.json();
    const o = j.quiz || j.data || j;
    return o._id || o.id || "";
  } catch (e) {
    return "";
  }
};

const shuffle = (arr) => {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};

// body for POST /api/quizzes (matches models/Quiz.js)
const quizBody = (quizQs) =>
  JSON.stringify({
    title: `Load Quiz ${randomString(5)}`,
    description: "Generated by k6",
    category: "Science",
    difficulty: pick(["easy", "medium", "hard"]),
    points: 20,
    questions: quizQs.slice(0, 3),
  });

// ---------- setup: fetch public data, create users per role, log in ----------
export function setup() {
  // Public API 1: randomuser.me (realistic names)
  let people = [];
  try {
    people = http
      .get("https://randomuser.me/api/?results=30&nat=in,us,gb")
      .json("results");
  } catch (e) {}
  if (!people || !people.length) {
    people = Array.from({ length: 30 }, () => ({
      name: { first: `Test${randomString(4)}`, last: `User${randomString(4)}` },
    }));
  }

  // Public API 2: Open Trivia DB (quiz questions + chat prompts)
  let trivia = [];
  try {
    trivia =
      http
        .get("https://opentdb.com/api.php?amount=10&category=17&type=multiple")
        .json("results") || [];
  } catch (e) {}

  const clean = (s) => s.replace(/&[#\w]+;/g, " ");
  const prompts = trivia.length
    ? trivia.map((q) => clean(q.question))
    : FALLBACK_PROMPTS;
  const quizQs = trivia.length
    ? trivia.map((q) => {
        const correct = clean(q.correct_answer);
        const options = shuffle([...q.incorrect_answers.map(clean), correct]);
        return {
          questionText: clean(q.question),
          options,
          correctAnswerIndex: options.indexOf(correct),
          explanation: "",
        };
      })
    : FALLBACK_PROMPTS.map((q) => ({
        questionText: q,
        options: ["A", "B", "C", "D"],
        correctAnswerIndex: 0,
        explanation: "",
      }));

  const tokens = { student: [], teacher: [], admin: [] };

  // more accounts = attempts spread across users, like real traffic
  const roles = [
    ...Array(STUDENTS).fill("student"),
    ...Array(TEACHERS).fill("teacher"),
  ];

  roles.forEach((role, i) => {
    const p = people[i % people.length];
    const u = {
      name: `${p.name.first} ${p.name.last}`,
      email: `${randomString(8)}@loadtest.dev`.toLowerCase(),
      password: `Pw@${randomString(8)}`,
      role,
    };
    const r = http.post(`${BASE}${P.register}`, JSON.stringify(u), {
      headers: J,
    });
    const l = http.post(
      `${BASE}${P.login}`,
      JSON.stringify({ email: u.email, password: u.password }),
      { headers: J },
    );
    console.log(`${role} register=${r.status} login=${l.status}`);
    const t = tokenOf(l);
    if (t) tokens[role].push(t);
  });

  // Admin cannot self-register: use the account created by createAdmin.js
  if (__ENV.ADMIN_EMAIL) {
    const l = http.post(
      `${BASE}${P.login}`,
      JSON.stringify({
        email: __ENV.ADMIN_EMAIL,
        password: __ENV.ADMIN_PASSWORD,
      }),
      { headers: J },
    );
    console.log(`admin login=${l.status}`);
    const t = tokenOf(l);
    if (t) tokens.admin.push(t);
  }

  if (!tokens.student.length)
    exec.test.abort(
      "No student token. Fix register/login paths or body fields.",
    );

  // Seed quizzes that students will open and submit during the test
  // (deleted again in teardown, which also removes their attempts)
  const seedQuizzes = [];
  if (tokens.admin.length) {
    for (let i = 0; i < 2; i++) {
      const c = http.post(
        `${BASE}/api/quizzes`,
        quizBody(quizQs),
        auth(tokens.admin[0]),
      );
      console.log(`seed quiz create=${c.status}`);
      const id = idOf(c);
      if (id) seedQuizzes.push({ id, n: Math.min(3, quizQs.length) });
    }
  }

  return { tokens, prompts, quizQs, seedQuizzes };
}

export function teardown(data) {
  if (!data.tokens.admin.length) return;
  data.seedQuizzes.forEach((sq) =>
    http.del(`${BASE}/api/quizzes/${sq.id}`, null, auth(data.tokens.admin[0])),
  );
}

function call(e, data, token) {
  const body = e.chat
    ? JSON.stringify({ [P.chatField]: pick(data.prompts) })
    : null;
  return http.request(
    e.m,
    `${BASE}${e.p}`,
    body,
    auth(token, {
      tags: { name: `${e.m} ${e.p}`, flow: e.chat ? "chat" : "api" },
    }),
  );
}

// Admin creates a quiz, then deletes it so the DB stays clean
function adminQuizCycle(data, token) {
  const c = http.post(
    `${BASE}/api/quizzes`,
    quizBody(data.quizQs),
    auth(token, { tags: { name: "POST /api/quizzes", flow: "api" } }),
  );
  let d = null;
  const id = idOf(c);
  if (id) {
    d = http.del(
      `${BASE}/api/quizzes/${id}`,
      null,
      auth(token, { tags: { name: "DELETE /api/quizzes/:id", flow: "api" } }),
    );
  }
  return { c, d };
}

// Student opens a seeded quiz in play mode and submits random answers
function studentQuizAttempt(data, token) {
  if (!data.seedQuizzes.length) return null;
  const sq = pick(data.seedQuizzes);
  const g = http.get(
    `${BASE}/api/quizzes/${sq.id}?mode=play`,
    auth(token, { tags: { name: "GET /api/quizzes/:id", flow: "api" } }),
  );
  const answers = Array.from({ length: sq.n }, () => randomIntBetween(0, 3));
  const s = http.post(
    `${BASE}/api/quizzes/${sq.id}/submit`,
    JSON.stringify({ answers }),
    auth(token, {
      tags: { name: "POST /api/quizzes/:id/submit", flow: "api" },
    }),
  );
  return { g, s };
}

// ---------- smoke: every endpoint once per role ----------
export function smoke(data) {
  const line = (res, role, label) =>
    console.log(
      `${okStatus(res) ? "PASS" : "FAIL"} ${res.status} ${role.padEnd(8)} ${label}${okStatus(res) ? "" : "  " + String(res.body).slice(0, 100)}`,
    );

  ENDPOINTS.forEach((e) => {
    const list = data.tokens[e.role];
    if (!list.length)
      return console.log(`SKIP ${e.role} ${e.m} ${e.p} (no token)`);
    line(call(e, data, list[0]), e.role, `${e.m} ${e.p}`);
    sleep(1);
  });

  // student quiz flow
  const att = studentQuizAttempt(data, data.tokens.student[0]);
  if (att) {
    line(att.g, "student", "GET /api/quizzes/:id?mode=play");
    line(att.s, "student", "POST /api/quizzes/:id/submit");
  } else {
    console.log("SKIP student  quiz open/submit (no seed quiz was created)");
  }

  // role enforcement: a teacher must NOT be able to create quizzes
  if (data.tokens.teacher.length) {
    const r = http.post(
      `${BASE}/api/quizzes`,
      quizBody(data.quizQs),
      auth(data.tokens.teacher[0]),
    );
    console.log(
      `${r.status === 403 ? "PASS" : "FAIL"} ${r.status} teacher  POST /api/quizzes (expected 403)`,
    );
  }

  // admin quiz create + delete
  if (data.tokens.admin.length) {
    const { c, d } = adminQuizCycle(data, data.tokens.admin[0]);
    line(c, "admin", "POST /api/quizzes");
    if (d) line(d, "admin", "DELETE /api/quizzes/:id");
    else
      console.log(
        "SKIP admin    DELETE /api/quizzes/:id (no quiz id in create response)",
      );
  }
}

// ---------- load: role-based traffic ----------
export function studentFlow(data) {
  const t = pick(data.tokens.student);

  ENDPOINTS.filter((e) => e.role === "student" && !e.chat).forEach((e) => {
    check(call(e, data, t), { [`student ${e.p}`]: okStatus });
  });

  const att = studentQuizAttempt(data, t);
  if (att) {
    check(att.g, { "student open quiz": okStatus });
    check(att.s, { "student submit quiz": okStatus });
  }
  sleep(randomIntBetween(1, 3));
}

export function teacherFlow(data) {
  if (!data.tokens.teacher.length) return;
  const t = pick(data.tokens.teacher);
  ENDPOINTS.filter((e) => e.role === "teacher").forEach((e) => {
    check(call(e, data, t), { [`teacher ${e.p}`]: okStatus });
  });
  sleep(randomIntBetween(1, 3));
}

export function adminFlow(data) {
  if (!data.tokens.admin.length) return;
  const t = data.tokens.admin[0];
  ENDPOINTS.filter((e) => e.role === "admin").forEach((e) => {
    check(call(e, data, t), { [`admin ${e.p}`]: okStatus });
  });
  const { c, d } = adminQuizCycle(data, t);
  check(c, { "admin create quiz": okStatus });
  if (d) check(d, { "admin delete quiz": okStatus });
  sleep(2);
}

export function chatFlow(data) {
  const e = ENDPOINTS.find((x) => x.chat);
  const res = call(e, data, pick(data.tokens.student));
  check(res, { "chat 200": (r) => r.status === 200 });

  if (res.status === 200) {
    chatOkMs.add(res.timings.duration);
  } else if (__ITER < 10) {
    let why = "";
    try {
      why = res.json("debug_error");
    } catch (err) {
      why = String(res.body).slice(0, 200);
    }
    console.log(`chat status=${res.status} error=${why}`);
  }

  sleep(randomIntBetween(2, 5));
}

const ramp = (fn, peak) => ({
  executor: "ramping-vus",
  exec: fn,
  stages: [
    { duration: "30s", target: peak },
    { duration: "1m", target: peak },
    { duration: "20s", target: 0 },
  ],
});

export const options = {
  setupTimeout: "180s", // creating many test accounts (bcrypt) can take a while
  ...(MODE === "smoke"
    ? {
        scenarios: {
          smoke: {
            executor: "shared-iterations",
            vus: 1,
            iterations: 1,
            exec: "smoke",
          },
        },
      }
    : {
        scenarios: {
          students: ramp("studentFlow", 12 * SCALE),
          teachers: ramp("teacherFlow", 4 * SCALE),
          admins: ramp("adminFlow", 1),
          // chat is optional: -e CHAT_VUS=0 skips it entirely
          ...(CHAT_VUS > 0 ? { chat: ramp("chatFlow", CHAT_VUS) } : {}),
        },
        thresholds: {
          http_req_failed: ["rate<0.05"],
          "http_req_duration{flow:api}": ["p(95)<1500"], // normal API endpoints
          ...(CHAT_VUS > 0
            ? { "http_req_duration{flow:chat}": ["p(95)<10000"] } // RAG chatbot (LLM call)
            : {}),
        },
      }),
};
